---
- name: Verify scenario without fluentd installation
  hosts: all
  gather_facts: true
  become: no
  tasks:

    - name: Assert splunk-otel-collector service is started
      ansible.windows.win_service:
        name: splunk-otel-collector
        state: started
      check_mode: yes

    - name: Assert fluentdwinsvc service is not installed
      ansible.windows.win_service:
        name: fluentdwinsvc
        state: absent
      check_mode: yes
